### ISSUE TITLE
Code changes in Oqtane core causes exception

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.module.blogs#27]
ILogManager namespace was changed to Oqtane.Infrastructure.Interfaces.ILogManager during code cleanup to reflect actual folder structure in solution.
Where to fix it? 

System.TypeLoadException: Could not load type 'Oqtane.Infrastructure.ILogManager' from assembly 'Oqtane.Server, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()

**Comment by sbwalker** [comment]
namespace was reverted back
